# ----------------------------------------------------------------------------
#           FILE: config.toml
#    DESCRIPTION: Hugo configuration file
#         AUTHOR: Zoltán Király <zoliky@gmail.com>
# ----------------------------------------------------------------------------

title        = "My New Hugo Site"
baseURL      = "http://example.org/"
languageCode = "en-US"
theme        = "basic"

[params]
  author = "Zoltan Kiraly"