# ----------------------------------------------------------------------------
#           FILE: config.toml
#    DESCRIPTION: Hugo configuration file
#         AUTHOR: Zoltán Király <zoliky@gmail.com>
# ----------------------------------------------------------------------------

title        = "New Hugo Site"
baseURL      = "https://yourdomain.com/"
languageCode = "en-US"
theme        = "basic"

# The number of posts per page
paginate = 2

# Site params
[params]
  author      = "Zoltan Kiraly"
  description = "New Hugo Site"
  images      = ["site-feature-image.jpg"]

[permalinks]
  posts = "posts/:year/:month/:slug"
  year  = "/posts/:slug/"
  month = "/posts/:slug/"

[taxonomies]
  year     = "year"
  month    = "month"
  tag      = "tags"
  category = "categories"

[related]
  threshold    = 80.0
  includeNewer = false
  toLower      = false

  [[related.indices]]
    name   = "keywords"
    weight = 100.0
  
  [[related.indices]]
    name   = "date"
    weight = 10.0

# Menus
[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
  
  [[menu.main]]
    name   = "About Us"
    url    = "/about"
    weight = 2

  [[menu.main]]
    name   = "Blog"
    url    = "/posts"
    weight = 3

  [[menu.main]]
    identifier = "services"
    name       = "Services"
    url        = "/services"
    weight     = 4
  
  # Sub-menu
#  [[menu.main]]
#    identifier = "marketing"
#    parent     = "services"
#    name       = "Marketing"
#    url        = "/marketing"
#    weight     = 4
  
  # Sub-sub-menu
#  [[menu.main]]
#    parent = "marketing"
#    name   = "SEO"
#    url    = "/seo"
#    weight = 4

[social]
  twitter = "zoliky"

  [[social.icon]]
    icon  = "icon-facebook"
    title = "Connect with us on Facebook"
    url   = "https://www.facebook.com/yourfacebook"

  [[social.icon]]
    icon  = "icon-twitter"
    title = "Follow us on Twitter"
    url   = "https://twitter.com/yourtwitter"
  
  [[social.icon]]
    icon  = "icon-email"
    title = "Contact us via email"
    url   = "mailto:youremail@example.com"