# ----------------------------------------------------------------------------
#           FILE: config.toml
#    DESCRIPTION: Hugo configuration file
#         AUTHOR: Zoltán Király <zoliky@gmail.com>
# ----------------------------------------------------------------------------

title        = "New Hugo Site"
baseURL      = "https://yourdomain.com/"
languageCode = "en-US"
theme        = "basic"

# Site params
[params]
  author      = "Zoltan Kiraly"
  description = "New Hugo Site"
  images      = ["site-feature-image.jpg"]

[permalinks]
  posts = "posts/:year/:month/:slug"
  year  = "/posts/:slug/"
  month = "/posts/:slug/"

[taxonomies]
  year     = "year"
  month    = "month"
  tag      = "tags"
  category = "categories"

[related]
  threshold    = 80.0
  includeNewer = false
  toLower      = false

  [[related.indices]]
    name   = "keywords"
    weight = 100.0
  
  [[related.indices]]
    name   = "date"
    weight = 10.0

# The number of posts per page
paginate = 10

# Menus
[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
  
  [[menu.main]]
    name   = "About Us"
    url    = "/about"
    weight = 2

  [[menu.main]]
    name   = "Blog"
    url    = "/posts"
    weight = 3

  # A three-level deep menu
  # Outer menu item
  [[menu.main]]
    identifier = "services"
    name       = "Services"
    url        = "/services"
    weight     = 4

  # Inner menu item
  [[menu.main]]
    identifier = "marketing"
    parent     = "services"
    name       = "Marketing"
    url        = "/marketing"
    weight     = 4

  # Inner inner menu item
  [[menu.main]]
    parent = "marketing"
    name   = "SEO"
    url    = "/seo"
    weight = 4

[social]
  twitter = "zoliky"