# ----------------------------------------------------------------------------
#           FILE: config.toml
#    DESCRIPTION: Hugo configuration file
#         AUTHOR: Zoltán Király <zoliky@gmail.com>
# ----------------------------------------------------------------------------

title        = "New Hugo Site"
baseURL      = "https://hugo-starter-duw3.onrender.com"
languageCode = "en-US"
theme        = "basic"
paginate     = 2 # The number of posts per page

pygmentsUseClasses = true

#disableLanguages = ["hu"]
defaultContentLanguage = "en"

# Site params
[params]
  author      = "Your Name"
  description = "New Hugo Site"
  copyright   = "Copyright {currentYear} King Web Solutions. All rights reserved."
  images      = ["site-social.png"]
  twittercard = true
  opengraph   = true

# Permalinks
[permalinks]
  posts = "posts/:year/:month/:slug"
  year  = "/posts/:slug/"
  month = "/posts/:slug/"

# Taxonomies
[taxonomies]
  year     = "year"
  month    = "month"
  tag      = "tags"
  category = "categories"

# Related content
[related]
  threshold    = 80.0
  includeNewer = false
  toLower      = false

  [[related.indices]]
    name   = "keywords"
    weight = 100.0
  
  [[related.indices]]
    name   = "date"
    weight = 10.0

[languages]
  [languages.en]
    weight = 1

    [[languages.en.menu.main]]
      name   = "Home"
      url    = "/"
      weight = 1
    
    [[languages.en.menu.main]]
      name   = "About Us"
      url    = "/about"
      weight = 2
    
    [[languages.en.menu.main]]
      name   = "Blog"
      url    = "/posts"
      weight = 3

    [[languages.en.menu.main]]
      identifier = "services"
      name       = "Services"
      url        = "/services"
      weight     = 4
    
    # Sub-menu
    [[languages.en.menu.main]]
      identifier = "marketing"
      parent     = "services"
      name       = "Marketing"
      url        = "/marketing"
      weight     = 4

    # Sub sub-menu
    [[languages.en.menu.main]]
      parent = "marketing"
      name   = "SEO"
      url    = "/seo"
      weight = 4

  [languages.hu]
    title        = "Új Hugo Weboldal"
    languageCode = "hu"
    weight       = 2
  
    [languages.hu.params]
      description = "Új Hugo Weboldal"

    [[languages.hu.menu.main]]
      name   = "Címlap"
      url    = "/"
      weight = 1

    [[languages.hu.menu.main]]
      name   = "Rólunk"
      url    = "/about"
      weight = 2

    [[languages.hu.menu.main]]
      name   = "Blog"
      url    = "/posts"
      weight = 3

    [[languages.hu.menu.main]]
      identifier = "services"
      name       = "Szolgáltatások"
      url        = "/services"
      weight     = 4
    
    # Sub-menu
    [[languages.hu.menu.main]]
      identifier = "marketing"
      parent     = "services"
      name       = "Marketing"
      url        = "/marketing"
      weight     = 4
    
    # Sub sub-menu
    [[languages.hu.menu.main]]
      parent = "marketing"
      name   = "SEO"
      url    = "/seo"
      weight = 4
  
[social]
  twitter = "zoliky"

  [[params.social]]
    icon  = "ico-facebook"
    title = "Connect with us on Facebook"
    url   = "https://www.facebook.com/zoliky"

  [[params.social]]
    icon  = "ico-twitter"
    title = "Follow us on Twitter"
    url   = "https://twitter.com/zoliky"
  
  [[params.social]]
    icon  = "ico-email"
    title = "Contact us via email"
    url   = "mailto:youremail@example.com"